apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pocket-stat
spec:
  selector:
    matchLabels:
      app: pocket-stat
  template:
    metadata:
      labels:
        app: pocket-stat
    spec:
      hostNetwork: true
      privileged: true
      imagePullPolicy: Always
      containers:
      - name: pocket-stat
        image: photoszzt/storage_stats
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
        ports:
        - containerPort: 50056
        volumeMounts:
        - mountPath: /var/log/pocket-stat
          name: var-log
      volumes:
      - name: var-log
        hostPath: 
          path: /home/admin/
          type: Directory
      nodeSelector:
        pocketnodetype: "dram"
