apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocket-namenode-deployment
spec:
  selector:
    matchLabels:
      app: pocket-namenode
  replicas: 1
  template:
    metadata:
      labels:
        app: pocket-namenode
    spec:
      hostNetwork: true
      hostname: pocket-namenode
      containers:
      - name: pocket-namenode
        #image: anakli/pocket-namenode-ctrl:shell
        image: anakli/pocket-namenode-ctrl:auto
        ports:
        - containerPort: 9070
      nodeSelector: 
        pocketnodetype: "metadata"
