apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: pocketcluster.k8s.local
spec:
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: {{.KOPS_STATE_STORE}}/pocketcluster.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-{{.POCKET_AWS_ZONE}}
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-{{.POCKET_AWS_ZONE}}
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.11.10
  masterPublicName: api.pocketcluster.k8s.local
  networkCIDR: {{.POCKET_VPC_NETWORK_CIDR}}
  networkID: {{.POCKET_VPC_ID}}
  networking:
    weave: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: {{.POCKET_VPC_PRIVATE_NETWORK_CIDR}}
    name: pocket-kube-private
    type: Private
    zone: {{.POCKET_AWS_ZONE}}
    id: {{.POCKET_VPC_PRIVATE_SUBNET_ID}}
    egress: {{.POCKET_NAT_ID}}
  - cidr: {{.POCKET_VPC_PUBLIC_NETWORK_CIDR}}
    name: pocket-kube-public
    type: Public
    zone: {{.POCKET_AWS_ZONE}}
    id: {{.POCKET_VPC_PUBLIC_SUBNET_ID}}
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: pocketcluster.k8s.local
  name: master-{{.POCKET_AWS_ZONE}}
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2020-07-20
  # image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200907
  machineType: m5.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-{{.POCKET_AWS_ZONE}}
  role: Master
  subnets:
  - pocket-kube-private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: pocketcluster.k8s.local
  name: dram-nodes
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2020-07-20
  # image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200907
  machineType: r5.2xlarge
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: dram-nodes
    spot: "true"
    pocketnodetype: "dram"
  rootVolumeSize: 12
  role: Node
  subnets:
  - pocket-kube-private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: pocketcluster.k8s.local
  name: metadata-nodes
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2020-07-20
  # image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200907
  machineType: m5.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: metadata-nodes
    spot: "true"
    pocketnodetype: "metadata"
  rootVolumeSize: 12
  role: Node
  subnets:
  - pocket-kube-private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: pocketcluster.k8s.local
  name: nvme-nodes
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2020-07-20
  # image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200907
  # image: ami-310a6249
  machineType: i3.2xlarge
  maxSize: 0
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: nvme-nodes
    spot: "false"
    pocketnodetype: "nvme"
  rootVolumeSize: 15
  role: Node
  subnets:
  - pocket-kube-private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: pocketcluster.k8s.local
  name: hdd-nodes
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2020-07-20
  # image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200907
  # image: ami-310a6249
  machineType: h1.2xlarge
  maxSize: 0
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: hdd-nodes
    spot: "false"
    pocketnodetype: "hdd"
  rootVolumeSize: 15
  role: Node
  subnets:
  - pocket-kube-private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: pocketcluster.k8s.local
  name: ssd-nodes
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2020-07-20
  # image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200907
  # image: ami-310a6249
  machineType: i2.2xlarge
  maxSize: 0
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: ssd-nodes
    spot: "false"
    pocketnodetype: "ssd"
  rootVolumeSize: 15
  role: Node
  subnets:
  - pocket-kube-private
